name: Comment on PR

on:
  pull_request:
    types:
      - opened

permissions: 
  issues: 
    write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR branch name
        id: branch
        run: echo "::set-output name=branch::${{ github.event.pull_request.head.ref }}"

      - name: Comment on PR
        run: |
          PR_BRANCH=${{ steps.branch.outputs.branch }}
          COMMENT_URL="https://app.axiom.co/imlunahey-9dym/dashboards/AnKGQpKhp60beP1LqK?v_filter_branch=${PR_BRANCH}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $TOKEN" \
            -d "{\"body\":\"[Dashboard Link]($COMMENT_URL)\"}" \
            $API_URL
