name: Comment on PR

on:
  pull_request:
    types:
      - opened

permissions: 
  pull-requests: 
    write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comment on PR
        uses: actions/github-script@v6
        env:
          COMMENT_URL: "https://app.axiom.co/imlunahey-9dym/dashboards/AnKGQpKhp60beP1LqK?v_filter_branch=${{ github.event.pull_request.head.ref }}"
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Here's the [dashboard](${process.env.COMMENT_URL})!`
            })
